baseURL = "https://jolly-sand-0c161d010.7.azurestaticapps.net/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
theme = "hugo-theme-learn"
[params]
themeVariant = "blue"
titleSeparator = ""
disableLandingPageButton = true
landingPageURL = "/reseaux/"
landingPageName = "<i class='fas fa-home'></i> Accueil"
disableSearch = true
disableInlineCopyToClipBoard = true
editURL = ""
author = "Antoine Tohmé"
logo = "images/logo.png"
