baseURL = "https://itmt-prof.com/reseaux/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
theme = "hugo-theme-learn"
[params]
themeVariant = "blue"
titleSeparator = ""
disableLandingPageButton = true
landingPageURL = "/reseaux/"
landingPageName = "<i class='fas fa-home'></i> Accueil"
disableSearch = true
disableInlineCopyToClipBoard = true
editURL = ""
author = "Antoine Tohmé"